version: '3.6'

services:
  url-short:
    build: ./docker/phalcon
    volumes:
      - ./url:/var/www/app:rw
    #ports:
    #  - 8080:80
  frontend:
    build: ./docker/phalcon
    volumes:
      - ./frontend:/var/www/app:rw
    ports:
      - 80:80
    links:
      - url-short
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_DB=test
    volumes:
      - db-data:/var/lib/postgresql/data
#    ports:
#      - 5001:5432

volumes:
  db-data: {}
